package com.yuja.evp.testclasses;

import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

import com.yuja.evp.pagetestmethods.QuizPageTestMethods;
import com.yuja.evp.reports.Report;
import com.yuja.evp.utilities.Driver;
import com.yuja.lms.moodle.MoodlePage;

import io.opentelemetry.exporter.logging.SystemOutLogExporter;

public class MoodleTest extends BaseTest {
	
	
	     String LTILinkName="'TEST AUTOMATION STAGING 1.3'";        
	     String videoName="videoforautomation";
	     String videoNameinstructor="videoforautomationinstructor";
	     String videoNameforPlaybackquiz="video for playback";
	     String audioName="audioforautomation";
	     String audioNameinstructor="audioforautomationinstrctor";
	     String documentName="automationdocument";
	     String documentNameinstructor="automationdocumentinstructor";
	     String QuizTitle= "moodlevideoquiz";
	     String playbackQuizTitle= "moodleplaybackquiz";
	     String question = "Fav lms";
	     String option1 = "moodle";
	     String option2 = "blackboard";
	     String fitbPossibleans1="moodle";
	     String fitbPossibleans2="blackboard";
	     String hint="new";
	     String studentFullName="student automation";
	     String studentNameinActivityLog="automation student";
	     String embedVideoName= "'videoforautomation'";
	     String embedAudioName="'audioforautomation'";
	     String embedDocumentName="'automationdocument'";
	     String embedVideoNameinstructor= "'videoforautomationinstructor'";
	     String embedAudioNameinstructor="'audioforautomationinstructor'";
	     String embedDocumentNameinstructor="'automationdocumentinstructor'";
	     String studentAnsForShortAnsQuestion="moodle";
	     String studentAnsForFitbQuestion="moodle";

	     String courseNameForQuizPublish = "AUTOMATION MOODLE COURSE";
	     String marks="100%";
	     String courseNameForAutoProvisioning="AUTOPROVISION";
	     String courseCodeForAutoProvisioning="AP";
	     String courseNameForManualnewProvisioning="MANUALPROVISIONNEW";
	     String courseCodeForManualnewProvisioning="MPN";
	     String courseNameForManualexistingProvisioning="MANUALPROVISIONEXISTING";
	     String courseCodeForManualexistingProvisioning="MPE";
	     String userNameforProvisioning="moodlenewuser";
	     String emailOfUserforProvisioning="moodleuser@yuja.com";
	     String passwordOfUserforProvisioning="jamNOW123/";
	     String courseforEnrollingUserforUserProvisioning="USER PROVISIONING";
	     String[] courseArrayforEnrollingUserforUserProvisioning={"USER PROVISIONING","USER PROVISIONING2","USER PROVISIONING3"};
	     String userRoleinMoodleCourse="Manager"; //can be Teacher corresponding yuja role is GroupOwner or Student corresponding yuja role is GroupMember
	     String userRoleinYujaCourse="GroupOwner";
	     String customToolName="TEST AUTOMATION STAGING 1.3";
	     String moodleToolNameOnConfiguration="TEST AUTOMATION STAGING 1.3";
	     String directoryPathForVideo="src\\fileResources\\lmsVideo";
         String directoryPathForAudio="src\\fileResources\\lmsAudio";
	     String directoryPathForDoc="src\\fileResources\\lmsDocument";


	
	  @Test(description="Moodle_create_publish_attend_gradebook_administrator_test")
	  @Parameters({"TestName"})
	public void Moodle_create_publish_attend_gradebook_administrator_test(String TestName) {
		MoodlePage mp = new MoodlePage();
		try {
			mp.loginCreateandPublishEmbedQuiz(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.password"),LTILinkName,videoName,QuizTitle,question,option1, option2,fitbPossibleans1, fitbPossibleans2,hint,prop.getProperty("Moodle.studentusername"), prop.getProperty("Moodle.password"), studentAnsForShortAnsQuestion,studentAnsForFitbQuestion,courseNameForQuizPublish,marks,studentFullName,studentNameinActivityLog);
		} 
		catch (Exception e) {
			System.out.println(e.getMessage());
			e.printStackTrace();
			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);
		}
	}
	  	  
		
		@Test(description="Moodle_create_publish_attend_gradebook_instructor_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_create_publish_attend_gradebook_instructor_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.loginCreateandPublishEmbedQuiz(prop.getProperty("Moodle.instructorusername"), prop.getProperty("Moodle.password"),LTILinkName,videoNameinstructor,QuizTitle,question,option1, option2,fitbPossibleans1, fitbPossibleans2,hint,prop.getProperty("Moodle.studentusername"), prop.getProperty("Moodle.password"), studentAnsForShortAnsQuestion,studentAnsForFitbQuestion,courseNameForQuizPublish,marks,studentFullName,studentNameinActivityLog);         

      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
     }
		
		
		 @Test(description="Moodle_create_playback_attend_gradebook_administrator_test")
		  @Parameters({"TestName"})
		public void Moodle_create_playback_attend_gradebook_administrator_test(String TestName) {
			MoodlePage mp = new MoodlePage();
			try {
				mp.loginCreateandEmbedPlaybackQuiz(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.password"),LTILinkName,videoNameforPlaybackquiz, playbackQuizTitle,prop.getProperty("Moodle.studentusername"), prop.getProperty("Moodle.password"), courseNameForQuizPublish ,marks,studentFullName,studentNameinActivityLog);
			} 
			catch (Exception e) {
				System.out.println(e.getMessage());
				e.printStackTrace();
				Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);
			}
	 }
		  	  
			
			@Test(description="Moodle_create_playback_attend_gradebook_instructor_test")                                                                                                                                                                                                                                                                          
	      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
	    	public void Moodle_create_playback_attend_gradebook_instructor_test(String TestName) {                                                                                                                                                                                                                                                                
	      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
	      		try {                                                                                                                                                                                                                                                                                                             
	      			mp.loginCreateandEmbedPlaybackQuiz(prop.getProperty("Moodle.instructorusername"), prop.getProperty("Moodle.password"),LTILinkName,videoNameforPlaybackquiz, playbackQuizTitle,prop.getProperty("Moodle.studentusername"), prop.getProperty("Moodle.password"), courseNameForQuizPublish ,marks,studentFullName,studentNameinActivityLog);         
	      		}                                                                                                                                                                                                                                                                                                                 
	      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
	      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
	      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
	      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
	      		}                                                                                                                                                                                                                                                                                                                 
	  }
			
		
		@Test(description="Moodle_embed_video_as_instructor_check_accessible_by_student_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_embed_video_as_instructor_check_accessible_by_student_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.loginEmbedMedia(prop.getProperty("Moodle.instructorusername"), prop.getProperty("Moodle.password"),videoNameinstructor,prop.getProperty("Moodle.studentusername"), prop.getProperty("Moodle.password"), embedVideoNameinstructor);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 

      	} 
          
		@Test(description="Moodle_embed_video_as_administrator_check_accessible_by_student_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_embed_video_as_administrator_check_accessible_by_student_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.loginEmbedMedia(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.password"),videoName,prop.getProperty("Moodle.studentusername"), prop.getProperty("Moodle.password"), embedVideoName);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
     }   
		
		@Test(description="Moodle_embed_audio_as_instructor_check_accessible_by_student_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_embed_audio_as_instructor_check_accessible_by_student_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.loginEmbedMedia(prop.getProperty("Moodle.instructorusername"), prop.getProperty("Moodle.password"),audioNameinstructor,prop.getProperty("Moodle.studentusername"), prop.getProperty("Moodle.password"), embedAudioNameinstructor);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 

      	  } 
		@Test(description="Moodle_embed_audio_as_administrator_check_accessible_by_student_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_embed_audio_as_administrator_check_accessible_by_student_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.loginEmbedMedia(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.password"),audioName,prop.getProperty("Moodle.studentusername"), prop.getProperty("Moodle.password"), embedAudioName);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
     }   
		
		@Test(description="Moodle_embed_document_as_instructor_check_accessible_by_student_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_embed_document_as_instructor_check_accessible_by_student_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.loginEmbedMedia(prop.getProperty("Moodle.instructorusername"), prop.getProperty("Moodle.password"),documentNameinstructor,prop.getProperty("Moodle.studentusername"), prop.getProperty("Moodle.password"), embedDocumentNameinstructor);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      	  } 
          
		@Test(description="Moodle_embed_document_as_administrator_check_accessible_by_student_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_embed_document_as_administrator_check_accessible_by_student_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.loginEmbedMedia(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.password"),documentName,prop.getProperty("Moodle.studentusername"), prop.getProperty("Moodle.password"), embedDocumentName);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
     } 
		
		
		@Test(description="Moodle_upload_videos_as_administrator_check_in_media_library_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_upload_videos_as_administrator_check_in_media_library_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.CIMMediaChooserMediaUpload(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.password"), directoryPathForVideo,LTILinkName);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
     } 
		
		
		@Test(description="Moodle_upload_video_as_instuctor_check_in_media_library_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_upload_videos_as_instuctor_check_in_media_library_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.CIMMediaChooserMediaUpload(prop.getProperty("Moodle.instructorusername"), prop.getProperty("Moodle.password"),directoryPathForVideo,LTILinkName);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
		
		
		@Test(description="Moodle_upload_audio_as_administrator_check_in_media_library_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_upload_audio_as_administrator_check_in_media_library_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.CIMMediaChooserMediaUpload(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.password"),directoryPathForAudio,LTILinkName);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      } 
		
		@Test(description="Moodle_upload_audio_as_instuctor_check_in_media_library_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_upload_audio_as_instuctor_check_in_media_library_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.CIMMediaChooserMediaUpload(prop.getProperty("Moodle.instructorusername"), prop.getProperty("Moodle.password"),directoryPathForAudio,LTILinkName);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 

      	 }
          
		@Test(description="Moodle_upload_doc_as_administrator_check_in_media_library_test")                                                                                                                                                                                                                                                                          

      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_upload_doc_as_administrator_check_in_media_library_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.CIMMediaChooserMediaUpload(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.password"),directoryPathForDoc,LTILinkName);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
     } 
		
		
		@Test(description="Moodle_upload_doc_as_instuctor_check_in_media_library_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_upload_doc_as_instuctor_check_in_media_library_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.CIMMediaChooserMediaUpload(prop.getProperty("Moodle.instructorusername"), prop.getProperty("Moodle.password"),directoryPathForDoc,LTILinkName);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  

		@Test(description="Moodle_check_autoprovisionofcourse")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_check_autoprovisionofcourse(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.checkAutoprovisionOfCourse(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.password"), courseNameForAutoProvisioning, courseCodeForAutoProvisioning, customToolName, moodleToolNameOnConfiguration,prop.getProperty("ManagerID"), prop.getProperty("Password"));         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
		
		@Test(description="Moodle_check_manualprovisioningof_newcourse")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_check_manualprovisioningof_newcourse(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.checkManualprovisionOfNewCourse(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.password"), courseNameForManualnewProvisioning, courseCodeForManualnewProvisioning,customToolName, moodleToolNameOnConfiguration,prop.getProperty("ManagerID"), prop.getProperty("Password"));       
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
		
		@Test(description="Moodle_check_manualprovisioningto_existingcourse")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_check_manualprovisioningto_existingcourse(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.checkManualprovisionToExistingCourse(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.password"), courseNameForManualexistingProvisioning, courseCodeForManualexistingProvisioning, customToolName, moodleToolNameOnConfiguration,prop.getProperty("ManagerID"), prop.getProperty("Password"));       
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
		
		@Test(description="Moodle_check_autoprovisioning_user")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_check_autoprovisioning_user(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.checkAutoprovisionOfUser(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.password"),prop.getProperty("ManagerID"), prop.getProperty("Password"),emailOfUserforProvisioning,userNameforProvisioning,passwordOfUserforProvisioning,courseforEnrollingUserforUserProvisioning,userRoleinMoodleCourse,userRoleinYujaCourse);
      					       
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
		@Test(description="Moodle_check_autoprovisioning_user_multipleCourses")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_check_autoprovisioning_user_multipleCourses(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.checkAutoprovisionOfUserinMultipleCourses(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.password"),prop.getProperty("ManagerID"), prop.getProperty("Password"),emailOfUserforProvisioning,userNameforProvisioning,passwordOfUserforProvisioning,courseArrayforEnrollingUserforUserProvisioning,userRoleinMoodleCourse,userRoleinYujaCourse);
      					       
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
		
		@Test(description="Moodle_check_manualprovisioning_newuser")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_check_manualprovisioning_newuser(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.checkManualprovisionOfUser(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.password"),prop.getProperty("ManagerID"), prop.getProperty("Password"),emailOfUserforProvisioning,userNameforProvisioning,passwordOfUserforProvisioning,courseforEnrollingUserforUserProvisioning,userRoleinMoodleCourse,userRoleinYujaCourse,"new","automation_student");
      					       
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
		@Test(description="Moodle_check_manualprovisioning_existinguser")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_check_manualprovisioning_existinguser(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.checkManualprovisionOfUser(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.password"),prop.getProperty("ManagerID"), prop.getProperty("Password"),emailOfUserforProvisioning,userNameforProvisioning,passwordOfUserforProvisioning,courseforEnrollingUserforUserProvisioning,userRoleinMoodleCourse,userRoleinYujaCourse,"existing","automation_student");
      					       
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }
		@Test(description="Check_role_mapping_unlocked")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Check_role_mapping_unlocked(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.roleMappingUserTypeUnlocked(prop.getProperty("ManagerID"), prop.getProperty("Password"),prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.password"),"Student");
      					       
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
		@Test(description="Check_role_mapping_locked_as_student")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Check_role_mapping_locked_as_student(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.roleMappingUserTypeLocked(prop.getProperty("ManagerID"), prop.getProperty("Password"),prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.password"),"Student",2);
      					       
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
		@Test(description="Check_role_mapping_locked_as_instructor")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Check_role_mapping_locked_as_instructor(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.roleMappingUserTypeLocked(prop.getProperty("ManagerID"), prop.getProperty("Password"),prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.password"),"Instructor",3);
      					       
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			Report.reportStep(Driver.getDriver(), "The test case did not complete all of its steps", "FAIL", false);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
                
                                                                                                                                                                                                                                                                                                                          }                                                                                                                                                                                                                                                                                                                 