package com.yuja.evp.testclasses;

import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

import com.yuja.evp.pagetestmethods.QuizPageTestMethods;

import com.yuja.lms.moodle.MoodlePage;

import io.opentelemetry.exporter.logging.SystemOutLogExporter;

public class MoodleTest extends BaseTest {
	
	//String username = prop.getProperty("UserID");
	     
	     String adminUserName ="automationadmin";
	     String adminPassword = "jamNOW123/"; 
	     String instuctorUserName = "automationinstructor"; 
	     String instuctorPassword = "jamNOW123/";
	     String LTILinkName="'Xavier LTI 1.3'";        
	     String videoName="videoforautomation";
	     String videoNameinstructor="videoforautomationinstructor";
	     String videoNameforPlaybackquiz="video for playback";
	     String audioName="audioforautomation";
	     String audioNameinstructor="audioforautomationinstrctor";
	     String documentName="automationdocument";
	     String documentNameinstructor="automationdocumentinstructor";
	     String QuizTitle= "moodlevideoquiz";
	     String playbackQuizTitle= "moodleplaybackquiz";
	     String question = "Fav lms";
	     String option1 = "moodle";
	     String option2 = "blackboard";
	     String fitbPossibleans1="moodle";
	     String fitbPossibleans2="blackboard";
	     String hint="new";
	     String studentUserName="automationstudent";
	     String studentFullName="student automation";
	     String studentNameinActivityLog="automation student";
	     String studentPassword="jamNOW123/";
	     String embedVideoName= "'videoforautomation'";
	     String embedAudioName="'audioforautomation'";
	     String embedDocumentName="'automationdocument'";
	     String embedVideoNameinstructor= "'videoforautomationinstructor'";
	     String embedAudioNameinstructor="'audioforautomationinstructor'";
	     String embedDocumentNameinstructor="'automationdocumentinstructor'";
	     String studentAnsForShortAnsQuestion="moodle";
	     String studentAnsForFitbQuestion="moodle";

	     String courseNameForQuizPublish = "AUTOMATION MOODLE COURSE";
	     String marks="100%"; 
	     String yujaAdminUserName="automation_manager";
	     String yujaAdminPassword="jamNOW123!@#123";
	     String courseNameForAutoProvisioning="AUTOPROVISION";
	     String courseCodeForAutoProvisioning="AP";
	     String courseNameForManualnewProvisioning="MANUALPROVISIONNEW";
	     String courseCodeForManualnewProvisioning="MPN";
	     String courseNameForManualexistingProvisioning="MANUALPROVISIONEXISTING";
	     String courseCodeForManualexistingProvisioning="MPE";
	     String userNameforProvisioning="moodlenewuser";
	     String emailOfUserforProvisioning="moodleuser@yuja.com";
	     String passwordOfUserforProvisioning="jamNOW123/";
	     String courseforEnrollingUserforUserProvisioning="USER PROVISIONING";
	     String[] courseArrayforEnrollingUserforUserProvisioning={"USER PROVISIONING","USER PROVISIONING2","USER PROVISIONING3"};
	     String userRoleinMoodleCourse="Manager"; //can be Teacher corresponding yuja role is GroupOwner or Student corresponding yuja role is GroupMember
	     String userRoleinYujaCourse="GroupOwner";
	     String customToolName="XAVIER 1.3";
	     String moodleToolNameOnConfiguration="XAVIER 1.3";
	     String directoryPathForVideo="src\\fileResources\\lmsVideo";
         String directoryPathForAudio="src\\fileResources\\lmsAudio";
	     String directoryPathForDoc="src\\fileResources\\lmsDocument";


	
	  @Test(description="Moodle_create_publish_attend_gradebook_administrator_test")
	  @Parameters({"TestName"})
	public void Moodle_create_publish_attend_gradebook_administrator_test(String TestName) {
		MoodlePage mp = new MoodlePage();
		try {
			mp.loginCreateandPublishEmbedQuiz(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.adminpassword"),LTILinkName,videoName,QuizTitle,question,option1, option2,fitbPossibleans1, fitbPossibleans2,hint,studentUserName, studentPassword, studentAnsForShortAnsQuestion,studentAnsForFitbQuestion,courseNameForQuizPublish,marks,studentFullName,studentNameinActivityLog);
		} 
		catch (Exception e) {
			System.out.println(e.getMessage());
			e.printStackTrace();
			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);
		}
	}
	  	  
		
		@Test(description="Moodle_create_publish_attend_gradebook_instructor_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_create_publish_attend_gradebook_instructor_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.loginCreateandPublishEmbedQuiz(prop.getProperty("Moodle.instructorusername"), prop.getProperty("Moodle.instructorpassword"),LTILinkName,videoNameinstructor,QuizTitle,question,option1, option2,fitbPossibleans1, fitbPossibleans2,hint,studentUserName, studentPassword, studentAnsForShortAnsQuestion,studentAnsForFitbQuestion,courseNameForQuizPublish,marks,studentFullName,studentNameinActivityLog);         

      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
     }
		
		
		 @Test(description="Moodle_create_playback_attend_gradebook_administrator_test")
		  @Parameters({"TestName"})
		public void Moodle_create_playback_attend_gradebook_administrator_test(String TestName) {
			MoodlePage mp = new MoodlePage();
			try {
				mp.loginCreateandEmbedPlaybackQuiz(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.adminpassword"),LTILinkName,videoNameforPlaybackquiz, playbackQuizTitle,studentUserName, studentPassword, courseNameForQuizPublish ,marks,studentFullName,studentNameinActivityLog);
			} 
			catch (Exception e) {
				System.out.println(e.getMessage());
				e.printStackTrace();
				reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);
			}
	 }
		  	  
			
			@Test(description="Moodle_create_playback_attend_gradebook_instructor_test")                                                                                                                                                                                                                                                                          
	      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
	    	public void Moodle_create_playback_attend_gradebook_instructor_test(String TestName) {                                                                                                                                                                                                                                                                
	      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
	      		try {                                                                                                                                                                                                                                                                                                             
	      			mp.loginCreateandEmbedPlaybackQuiz(prop.getProperty("Moodle.instructorusername"), prop.getProperty("Moodle.instructorpassword"),LTILinkName,videoNameforPlaybackquiz, playbackQuizTitle,studentUserName, studentPassword, courseNameForQuizPublish ,marks,studentFullName,studentNameinActivityLog);         
	      		}                                                                                                                                                                                                                                                                                                                 
	      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
	      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
	      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
	      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
	      		}                                                                                                                                                                                                                                                                                                                 
	  }
			
		
		@Test(description="Moodle_embed_video_as_instructor_check_accessible_by_student_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_embed_video_as_instructor_check_accessible_by_student_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.loginEmbedMedia(prop.getProperty("Moodle.instructorusername"), prop.getProperty("Moodle.instructorpassword"),videoNameinstructor,studentUserName, studentPassword, embedVideoNameinstructor);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 

      	} 
          
		@Test(description="Moodle_embed_video_as_administrator_check_accessible_by_student_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_embed_video_as_administrator_check_accessible_by_student_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.loginEmbedMedia(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.adminpassword"),videoName,studentUserName, studentPassword, embedVideoName);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
     }   
		
		@Test(description="Moodle_embed_audio_as_instructor_check_accessible_by_student_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_embed_audio_as_instructor_check_accessible_by_student_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.loginEmbedMedia(prop.getProperty("Moodle.instructorusername"), prop.getProperty("Moodle.instructorpassword"),audioNameinstructor,studentUserName, studentPassword, embedAudioNameinstructor);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 

      	  } 
		@Test(description="Moodle_embed_audio_as_administrator_check_accessible_by_student_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_embed_audio_as_administrator_check_accessible_by_student_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.loginEmbedMedia(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.adminpassword"),audioName,studentUserName, studentPassword, embedAudioName);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
     }   
		
		@Test(description="Moodle_embed_document_as_instructor_check_accessible_by_student_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_embed_document_as_instructor_check_accessible_by_student_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.loginEmbedMedia(instuctorUserName, instuctorPassword,documentNameinstructor,studentUserName, studentPassword, embedDocumentNameinstructor);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      	  } 
          
		@Test(description="Moodle_embed_document_as_administrator_check_accessible_by_student_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_embed_document_as_administrator_check_accessible_by_student_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.loginEmbedMedia(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.adminpassword"),documentName,studentUserName, studentPassword, embedDocumentName);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
     } 
		
		
		@Test(description="Moodle_upload_videos_as_administrator_check_in_media_library_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_upload_videos_as_administrator_check_in_media_library_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.CIMMediaChooserMediaUpload(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.adminpassword"), directoryPathForVideo,LTILinkName);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
     } 
		
		
		@Test(description="Moodle_upload_video_as_instuctor_check_in_media_library_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_upload_videos_as_instuctor_check_in_media_library_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.CIMMediaChooserMediaUpload(instuctorUserName, instuctorPassword,directoryPathForVideo,LTILinkName);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
		
		
		@Test(description="Moodle_upload_audio_as_administrator_check_in_media_library_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_upload_audio_as_administrator_check_in_media_library_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.CIMMediaChooserMediaUpload(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.adminpassword"),directoryPathForAudio,LTILinkName);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      } 
		
		@Test(description="Moodle_upload_audio_as_instuctor_check_in_media_library_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_upload_audio_as_instuctor_check_in_media_library_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.CIMMediaChooserMediaUpload(instuctorUserName, instuctorPassword,directoryPathForAudio,LTILinkName);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 

      	 }
          
		@Test(description="Moodle_upload_doc_as_administrator_check_in_media_library_test")                                                                                                                                                                                                                                                                          

      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_upload_doc_as_administrator_check_in_media_library_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.CIMMediaChooserMediaUpload(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.adminpassword"),directoryPathForDoc,LTILinkName);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
     } 
		
		
		@Test(description="Moodle_upload_doc_as_instuctor_check_in_media_library_test")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_upload_doc_as_instuctor_check_in_media_library_test(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.CIMMediaChooserMediaUpload(instuctorUserName, instuctorPassword,directoryPathForDoc,LTILinkName);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  

		@Test(description="Moodle_check_autoprovisionofcourse")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_check_autoprovisionofcourse(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.checkAutoprovisionOfCourse(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.adminpassword"), courseNameForAutoProvisioning, courseCodeForAutoProvisioning, customToolName, moodleToolNameOnConfiguration,yujaAdminUserName,yujaAdminPassword);         
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
		
		@Test(description="Moodle_check_manualprovisioningof_newcourse")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_check_manualprovisioningof_newcourse(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.checkManualprovisionOfNewCourse(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.adminpassword"), courseNameForManualnewProvisioning, courseCodeForManualnewProvisioning,customToolName, moodleToolNameOnConfiguration,yujaAdminUserName,yujaAdminPassword);       
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
		
		@Test(description="Moodle_check_manualprovisioningto_existingcourse")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_check_manualprovisioningto_existingcourse(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.checkManualprovisionToExistingCourse(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.adminpassword"), courseNameForManualexistingProvisioning, courseCodeForManualexistingProvisioning, customToolName, moodleToolNameOnConfiguration,yujaAdminUserName,yujaAdminPassword);       
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
		
		@Test(description="Moodle_check_autoprovisioning_user")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_check_autoprovisioning_user(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.checkAutoprovisionOfUser(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.adminpassword"),yujaAdminUserName,yujaAdminPassword,emailOfUserforProvisioning,userNameforProvisioning,passwordOfUserforProvisioning,courseforEnrollingUserforUserProvisioning,userRoleinMoodleCourse,userRoleinYujaCourse);
      					       
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
		@Test(description="Moodle_check_autoprovisioning_user_multipleCourses")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_check_autoprovisioning_user_multipleCourses(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.checkAutoprovisionOfUserinMultipleCourses(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.adminpassword"),yujaAdminUserName,yujaAdminPassword,emailOfUserforProvisioning,userNameforProvisioning,passwordOfUserforProvisioning,courseArrayforEnrollingUserforUserProvisioning,userRoleinMoodleCourse,userRoleinYujaCourse);
      					       
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
		
		@Test(description="Moodle_check_manualprovisioning_newuser")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_check_manualprovisioning_newuser(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.checkManualprovisionOfUser(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.adminpassword"),yujaAdminUserName,yujaAdminPassword,emailOfUserforProvisioning,userNameforProvisioning,passwordOfUserforProvisioning,courseforEnrollingUserforUserProvisioning,userRoleinMoodleCourse,userRoleinYujaCourse,"new","automation_student");
      					       
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
		@Test(description="Moodle_check_manualprovisioning_existinguser")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Moodle_check_manualprovisioning_existinguser(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.checkManualprovisionOfUser(prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.adminpassword"),yujaAdminUserName,yujaAdminPassword,emailOfUserforProvisioning,userNameforProvisioning,passwordOfUserforProvisioning,courseforEnrollingUserforUserProvisioning,userRoleinMoodleCourse,userRoleinYujaCourse,"existing","automation_student");
      					       
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }
		@Test(description="Check_role_mapping_unlocked")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Check_role_mapping_unlocked(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.roleMappingUserTypeUnlocked(yujaAdminUserName,yujaAdminPassword,prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.adminpassword"),"Student");
      					       
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
		@Test(description="Check_role_mapping_locked_as_student")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Check_role_mapping_locked_as_student(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.roleMappingUserTypeLocked(yujaAdminUserName,yujaAdminPassword,prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.adminpassword"),"Student",2);
      					       
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
		@Test(description="Check_role_mapping_locked_as_instructor")                                                                                                                                                                                                                                                                          
      	@Parameters({"TestName"})                                                                                                                                                                                                                                                                                        
    	public void Check_role_mapping_locked_as_instructor(String TestName) {                                                                                                                                                                                                                                                                
      		MoodlePage mp = new MoodlePage();                                                                                                                                                                                                                                                                                 
      		try {                                                                                                                                                                                                                                                                                                             
      			mp.roleMappingUserTypeLocked(yujaAdminUserName,yujaAdminPassword,prop.getProperty("Moodle.adminusername"), prop.getProperty("Moodle.adminpassword"),"Instructor",3);
      					       
      		}                                                                                                                                                                                                                                                                                                                 
      		catch (Exception e) {                                                                                                                                                                                                                                                                                             
      			System.out.println(e.getMessage());                                                                                                                                                                                                                                                                              
      			e.printStackTrace();                                                                                                                                                                                                                                                                                             
      			reportStep("@Method "+Scenario_Name +" exception to be handled", "FAIL", true);                                                                                                                                                                                                                                  
      		}                                                                                                                                                                                                                                                                                                                 
      }  
                
                                                                                                                                                                                                                                                                                                                          }                                                                                                                                                                                                                                                                                                                 